name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  version: 2.5.0
  key: dein:colorify
  organization: dein
  name: Colorify

jobs:
  build:
    runs-on: ubuntu-latest
    name: dotnet build
    steps:
      - uses: actions/checkout@v2
      - name: setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: install sonar-scanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: restore
        run: dotnet restore Colorify/Colorify.csproj
      - name: build
        run: dotnet build Colorify/Colorify.csproj --no-restore
      - name: restore test
        run: dotnet restore Colorify.Tests/Colorify.Tests.csproj
      - name: build test
        run: dotnet build Colorify.Tests/Colorify.Tests.csproj --no-restore
      - name: scanner begin
        run: dotnet sonarscanner begin /k:"${{ env.key }}" /n:"${{ env.name }}" /v:"${{ env.version }}" /o:"${{ env.organization }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml"
      - name: scanner build
        run: dotnet build Colorify/Colorify.csproj
      - name: scanner test
        run: dotnet test Colorify.Tests/Colorify.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
      - name: scanner end
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
