name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  version: 2.5.0

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: restore
        run: dotnet restore Colorify/Colorify.csproj
      - name: build
        run: dotnet build Colorify/Colorify.csproj
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.2
        with:
          buildCommand: dotnet build Colorify/Colorify.csproj
          testCommand: dotnet test Colorify.Tests/Colorify.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
          projectKey: dein:colorify
          projectName: Colorify
          sonarOrganisation: dein
          beginArguments: >
            /k:"dein:colorify"
            /n:"Colorify"
            /v:"${{ env.version }}"
            /o:"dein"
            /d:sonar.verbose="true"
            /d:sonar.language="cs"
            /d:sonar.exclusions="**/bin/**/*,**/obj/**/*"
            /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
