name: pack

on:
  push:
    tags:
      - "v*"

env:
  dotnet: 3.1.201
  version: 2.5.0
  key: dein:colorify
  organization: dein
  name: Colorify

jobs:
  pack:
    runs-on: ubuntu-latest
    name: pack
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: set environment
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: create file
        run: dotnet pack Colorify/Colorify.csproj /p:NuspecFile=${{ env.workspace }}/Colorify/Colorify.nuspec -c release
      - name: publish github
        run: dotnet nuget push "bin/release/dein.Colorify.${{ env.version }}.nupkg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
