name: pack

on:
  push:
    tags:
      - "v*"

env:
  dotnet: 6.0.201
  version: 2.7.0

jobs:
  pack:
    runs-on: ubuntu-latest
    name: packing
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: set environment
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: setup nuget config
        run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' "${{ env.workspace }}/Package/nuget.config" > nuget.config
      - name: create file
        run: dotnet pack Colorify/Colorify.csproj /p:NuspecFile=${{ env.workspace }}/Colorify/Colorify.nuspec -o ${{ env.workspace }}/Package/ -c release
      - name: publish nuget on microsoft
        run: dotnet nuget push "${{ env.workspace }}/Package/dein.Colorify.${{ env.version }}.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s "nuget" --skip-duplicate --no-symbols true
      - name: publish nuget on github
        run: dotnet nuget push "${{ env.workspace }}/Package/dein.Colorify.${{ env.version }}.nupkg" -s "github" --skip-duplicate --no-symbols true
  tweet:
    runs-on: ubuntu-latest
    name: message
    needs: pack
    steps:
      - uses: actions/checkout@v2
      - name: setup Twitter
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Colorify - C# .Net Console Library with Text Format: colors, alignment and lot more [ Win+Mac+Linux ]\n
          ${{ env.version }} 🐛🛠 version available as NuGet package\n
          $ dotnet add package dein.colorify\n
          \n
          https://github.com/deinsoftware/colorify"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
