name: pack

on:
  release:
    types: [published]

env:
  dotnet: 7.0.101
  version: 2.9.0

jobs:
  pack:
    runs-on: ubuntu-latest
    name: packing
    steps:
      - uses: actions/checkout@v2
      - name: setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet }}
      - name: setup nuget config
        run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' "${{ github.workspace }}/Package/nuget.config" > nuget.config
      - name: create file
        run: dotnet pack Colorify/Colorify.csproj /p:NuspecFile=${{ github.workspace }}/Colorify/Colorify.nuspec -o ${{ github.workspace }}/Package/ -c release
      - name: publish nuget on microsoft
        run: dotnet nuget push "${{ github.workspace }}/Package/dein.Colorify.${{ env.version }}.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s "nuget" --skip-duplicate --no-symbols
      - name: publish nuget on github
        run: dotnet nuget push "${{ github.workspace }}/Package/dein.Colorify.${{ env.version }}.nupkg" -s "github" --skip-duplicate --no-symbols

  tweet:
    needs: pack
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Eomm/why-don-t-you-tweet@v1
        if: ${{ !github.event.repository.private }}
        with:
          tweet-message: "Colorify ${{ github.event.release.tag_name }} 🐛🛠 is here 🥳\n
          C# .Net Console Library with Text Format: colors, alignment and lot more [ Win+Mac+Linux ]\n\n
          $ dotnet add package dein.colorify\n\n
          #dotnet #csharp #cli\n\n
          https://github.com/deinsoftware/colorify"
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
